Repository JackalLabs/canine-chain, pull requests merged in 2023-11, with the labels that each got.

#377 Deps: Updating merkle tree library
  go.mod
  go.sum
  x/storage/keeper/msg_server_proofs_test.go
  x/storage/simulation/utils.go
  x/storage/types/file_deal.go
  x/storage/types/file_deal_test.go
  x/storage/utils/trees.go
Labels: dependencies

#382 proto formatting and comment updates and standardization
  proto/canine_chain/filetree/genesis.proto
  proto/canine_chain/filetree/params.proto
  proto/canine_chain/filetree/query.proto
  proto/canine_chain/filetree/tx.proto
  proto/canine_chain/jklmint/genesis.proto
  proto/canine_chain/jklmint/params.proto
  proto/canine_chain/jklmint/query.proto
  proto/canine_chain/jklmint/tx.proto
  proto/canine_chain/notifications/genesis.proto
  proto/canine_chain/notifications/noti_counter.proto
  proto/canine_chain/notifications/notifications.proto
  proto/canine_chain/notifications/params.proto
  proto/canine_chain/notifications/query.proto
  proto/canine_chain/notifications/tx.proto
  proto/canine_chain/oracle/feed.proto
  proto/canine_chain/oracle/genesis.proto
  proto/canine_chain/oracle/params.proto
  proto/canine_chain/oracle/query.proto
  proto/canine_chain/oracle/tx.proto
  proto/canine_chain/rns/forsale.proto
  proto/canine_chain/rns/genesis.proto
  proto/canine_chain/rns/params.proto
  proto/canine_chain/rns/query.proto
  proto/canine_chain/rns/tx.proto
  proto/canine_chain/storage/active_deals.proto
  proto/canine_chain/storage/genesis.proto
  proto/canine_chain/storage/params.proto
  proto/canine_chain/storage/payment_info.proto
  proto/canine_chain/storage/providers.proto
  proto/canine_chain/storage/query.proto
  proto/canine_chain/storage/tx.proto
Labels: enhancement

#384 Fix: Providers no longer burn files randomly
  proto/canine_chain/storage/params.proto
  proto/canine_chain/storage/tx.proto
  scripts/bulk-upload.sh
  scripts/test-sequoia.sh
  x/storage/client/cli/tx_post_file.go
  x/storage/keeper/migrations.go
  x/storage/keeper/msg_server_buy_storage_test.go
  x/storage/keeper/msg_server_postproof.go
  x/storage/keeper/msg_server_proofs_test.go
  x/storage/keeper/msg_server_upgrade_storage_test.go
  x/storage/keeper/rewards.go
  x/storage/keeper/rewards_test.go
  x/storage/legacy/v5/store.go
  x/storage/legacy/v5/types.go
  x/storage/types/file.go
  x/storage/types/file_deal.go
  x/storage/types/message_postproof.go
  x/storage/types/params.go
  x/storage/types/params.pb.go
  x/storage/types/proof_loader.go
  x/storage/types/tx.pb.go
Labels: bug
