Repository JackalLabs/canine-chain, pull requests merged in 2023-01, with the labels that each got.

#203 Jkl 198 msg buy storage bug fix & simulation implementation
  app/app_test.go
  app/sim_test.go
  proto/canine_chain/storage/genesis.proto
  x/storage/genesis.go
  x/storage/keeper/msg_server_buy_storage.go
  x/storage/keeper/msg_server_buy_storage_test.go
  x/storage/keeper/msg_server_postproof.go
  x/storage/keeper/rewards.go
  x/storage/keeper/utils.go
  x/storage/module_simulation.go
  x/storage/simulation/buy_storage.go
  x/storage/simulation/cancel_contract.go
  x/storage/simulation/genesis.go
  x/storage/simulation/init_miner.go
  x/storage/simulation/param.go
  x/storage/simulation/post_contract.go
  x/storage/simulation/postproof.go
  x/storage/simulation/sign_contract.go
  x/storage/simulation/utils.go
  x/storage/types/genesis.go
  x/storage/types/genesis.pb.go
  x/storage/types/params.go
Labels: bug

#211 switching to informal systems tendermint fork
  go.mod
  go.sum
Labels: dependencies

#213 Fix for Buying, Added Update
  proto/canine_chain/rns/tx.proto
  x/rns/client/cli/tx.go
  x/rns/client/cli/tx_update.go
  x/rns/keeper/msg_server_basics_test.go
  x/rns/keeper/msg_server_buy.go
  x/rns/keeper/msg_server_buy_test.go
  x/rns/keeper/msg_server_register.go
  x/rns/keeper/msg_server_update.go
  x/rns/types/message_update.go
  x/rns/types/tx.pb.go
Labels: bug, enhancement

#218 Sha512 merkle tree upgrade
  go.mod
  go.sum
  x/storage/keeper/msg_server_postproof.go
  x/storage/keeper/msg_server_proofs_test.go
  x/storage/simulation/utils.go
  x/storage/types/sha512/sha512.go
Labels: enhancement

#220 Removing old contracts after 100 blocks
  proto/canine_chain/storage/contracts.proto
  x/storage/abci.go
  x/storage/client/cli/tx_post_contract.go
  x/storage/keeper/contract_killing.go
  x/storage/keeper/msg_server_post_contract.go
  x/storage/types/contracts.pb.go
Labels: enhancement

#231 Fix upgrade
  app/upgrades/testnet/fixstrays/store.go
  app/upgrades/testnet/fixstrays/upgrades.go
  scripts/upgrade-test.sh
  x/storage/keeper/migrations.go
  x/storage/module.go
Labels: bug
